version: "3.3"
services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: GraphQL
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - 8081:8081
        env_file:
            - .env
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
        depends_on:
            - mongo
    4790project:
        build: .
        ports:
            - "6060:6060"
        