version: "3.8"
services:
  postgres:
    image: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  graphql:
    build: ./prisma
    ports:
      - '4000:4000'
    volumes:
      - ./prisma:/prisma
      - /primsa/node_modules
      - ./prisma/data:/prisma/data
    stdin_open: true
    tty: true
    depends_on:
      - postgres
  
  backend:
    build: ./
    ports:
      - '6060:6060'
    volumes:
      - /node_modules
    env_file:
      - ./.env
    
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/client/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata: